# Generated by Django 6.0.6 on 2026-08-11 20:12

from django.db import migrations


def fill_new_building_fields(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.filter(construction_year__gte=2015).update(new_building=True)
    Flat.objects.filter(construction_year__lt=2015).update(new_building=False)
    Flat.objects.filter(construction_year__isnull=True).update(new_building=False)


def unfill_new_building_fields(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.filter(new_building__isnull=False).update(new_building=None)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(fill_new_building_fields, unfill_new_building_fields),
    ]
