# Generated by Django 6.0.6 on 2026-08-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owner_phone_number',
            field=models.CharField(max_length=20, verbose_name='Номер владельца'),
        ),
    ]
