# Generated by Django 6.0.6 on 2026-08-13 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_link_owners_and_flats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_phone',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
    ]
